"""Auto migration

Revision ID: 38d8a986e85f
Revises: 7529c1324845
Create Date: 2026-04-21 22:54:38.821581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d8a986e85f'
down_revision = '7529c1324845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
