"""Auto migration

Revision ID: 52233fadd423
Revises: 68793ffea927
Create Date: 2026-04-20 00:28:47.651928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52233fadd423'
down_revision = '68793ffea927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
