"""Auto migration

Revision ID: 68793ffea927
Revises: 
Create Date: 2026-04-19 22:51:08.584309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68793ffea927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('last_seen_date')

    # ### end Alembic commands ###
