"""Auto migration

Revision ID: 7529c1324845
Revises: 52233fadd423
Create Date: 2026-04-20 01:23:02.998953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7529c1324845'
down_revision = '52233fadd423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
